### ISSUE TITLE
Create leaflet map revealing case counts by parcel

### ISSUE THREAD

**Issue by edarsow** [TechnologyRediscovery/codenforce#38]
## Short-term Goal
Provide authenticated users in codeNforce a slippy map containing parcel outlines for their current municipality, each of which is connected to a data bundle containing the parcel's ID, address, and counts of CE cases, occ periods, etc.

## Tool chain preliminary vision
We have the workflow for loading in spatial data into our postgreSQL data store which has postGIS extensions enabled. Once a geometry column exists for each parcel, we want to write a SQL statement to count cases by parcel and attach that value to each parcel, and export that data via some interchange format like geoJSON so that Leaflet or a different mapping front-end can ingest and visualize.

## Questions
1. What does map box do that Leaflet does/does not do? Do they work together?
2. What tools make sense to use for inputting data from the user's interaction with the map into the database? For example, what if the user wants to click on the four properties he/she wants to visit that day and have that sequence loaded into their workflow for the day? Or What if the user wants to click on a parcel and mark it for enforcement priority, or to print a case profile?

## Longer-term mapping goal: 
Create a case exploration tool that allows the user to click on a parcel and then explore existing code enforcement cases and occupancy periods associated with that property in a side panel, allowing for in-depth exploration of case details, such as violations chapter/section, compliance deadlines, etc.

**Comment by edarsow** [comment]
Scheduled a consult with Gabriel this week.

**Comment by wwalk3** [comment]
Successfully created map object taking in data from DB, converting into GeoJSON object, and rendering on map. Individual parcels display info from database table and can be filtered on map (current filter is by zip code). 

Current working questions/objectives:
* Is it possible to populate dynamic variables in filter drop down menu at runtime? 
* Populate markers for parcels of interest when map scope is narrow via filters (eg. for CE: which parcels have open cases?)
* Troubleshoot broken map logo image
* Color code regions dynamically

Bigger questions:
* What kind of data can/should be mutable by user?
* What are the possibilities for the map tool to be the main interface for CodeNforce entirely? What considerations would be necessary now for that functionality in the future?

Asks/Concerns/Misc:
* I need update of the database with dummy populated data, in order to test on parcels with attached geometries and case instances.
* Taking a look at Zillow's tech stack for inspo.

Current working languages/libraries/frameworks:
* JavaScript, HTML/CSS, SQL
* PostgreSQL, Express.js, Node.js, PUG, Leaflet.js

**Comment by wwalk3** [comment]
Having an issue upon migration in installing PostGIS extension onto the remote database, in order to migrate the spatial data necessary to run the map.
