### ISSUE TITLE
Create a PublicInfoBundleOccPeriod subclass

### ISSUE THREAD

**Issue by edarsow** [TechnologyRediscovery/codenforce#75]
Using the info sublass `PublicInfoBundleCECase` as a model, create a subclass called `PublicInfoBundleOccPeriod` which contains a subset of fields from the `OccPeriod` and/or `OccPeriodDataHeavy` for release to the public. 

This may involve creating new flags on the `OccPeriod` object for controlling release of certain info, such as inspection status, permits etc. Perhaps that might also involve public release flags on sub-objects inside a `OccPeriod`, such as an `OccupancyPermit`. 

Design principle: Release data to the public when there's not an immediately clear reason not to do so, such as preserving the identities of tenant names or past addresses.

## Persons
One key component of occupancy is tracking who lives where, which means dealing with `Person` objects. Dominic Pimpinella has already created the notion of an anonymized person which doesn't yet have its own subclass. But there are methods on `PersonCoordinator` that take in a `Person` and  'x' out some components of identifying info before display to a public user. 

As part of this strategy development, review this existing system and probably create a dedicated subclass of `Person` called something like `PersonPublic` which we can comfortably send to the public data portal without fear of dumping somebody's 3 phone numbers and dog's name to the world.

Given a new object like `PersonPublic` our  new `PublicInfoBundleOccPeriod` object that is the subject of this issue should then contain a `List<PersonPublic>` rather than a plain old `List<Person>`

See Screen shot:
![image](https://user-images.githubusercontent.com/10214958/83534376-c4c1d400-a4be-11ea-8bb7-e2096d813aa9.png)

**Comment by NADGIT** [comment]
As I'm working on this, I have a bit of an addition to my philosophy: When storing a list or an object that needs to be public-ready on a PublicInfoBundle, I think it would be best to use the PublicInfoBundle for that object.

That's a really confusing way to phrase it, but here's an example: instead of using a list of persons within the OccPeriod, create a list of PublicInfoBundlePersons in the PublicInfoBundleOccPeriod. This way you can filter the Person objects through the Coordinator extract method and then pull them back out using the export methods.

**Comment by NADGIT** [comment]
I've completed this task and my changes were merged into recovered, so I'll close this now.
